version: '3.9'

services:    
  serv-apache:
    image: php:7.4-apache
    container_name: serv-apache
    ports:
      - "1234:80"
    restart: always
    volumes:
      - ./www:/var/www/html
    links:
      - db-mysql
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  db-mysql:
    image: mysql:8
    container_name: db-mysql
    environment:
      MYSQL_DATABASE: prueba-tec
      MYSQL_ROOT_PASSWORD: pswdummy1
    ports:
      - "4321:3306"
    restart: always
    volumes:
      - ./db:/var/lib/mysql


      